name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Force Gradle 8.13 and clear cache
        run: |
          echo "=== Before update ==="
          grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties
          ./gradlew --version || true
          
          echo "=== Clearing Gradle cache ==="
          rm -rf ~/.gradle/caches || true
          rm -rf ~/.gradle/wrapper || true
          rm -rf .gradle || true
          
          echo "=== Updating to Gradle 8.13 ==="
          sed -i.bak 's|gradle-.*-bin\.zip|gradle-8.13-bin.zip|' gradle/wrapper/gradle-wrapper.properties
          
          echo "=== After update ==="
          grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties
          
          echo "=== Downloading fresh Gradle ==="
          ./gradlew --version
          
          echo "=== Verifying Gradle version ==="
          ./gradlew --version | grep "Gradle 8.13" || (echo "ERROR: Gradle 8.13 not detected" && exit 1)

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v3-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v3-

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-outputs
          path: app/build/outputs/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: app/build/test-results/

  android-test:
    runs-on: macos-14
    env:
      MD_DEVICE_TASK: ":app:pixel7Api35DebugAndroidTest"

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Force Gradle 8.13 and clear cache
        run: |
          echo "=== Before update ==="
          grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties
          ./gradlew --version || true
          
          echo "=== Clearing Gradle cache ==="
          rm -rf ~/.gradle/caches || true
          rm -rf ~/.gradle/wrapper || true
          rm -rf .gradle || true
          
          echo "=== Updating to Gradle 8.13 ==="
          sed -i.bak 's|gradle-.*-bin\.zip|gradle-8.13-bin.zip|' gradle/wrapper/gradle-wrapper.properties
          
          echo "=== After update ==="
          grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties
          
          echo "=== Downloading fresh Gradle ==="
          ./gradlew --version
          
          echo "=== Verifying Gradle version ==="
          ./gradlew --version | grep "Gradle 8.13" || (echo "ERROR: Gradle 8.13 not detected" && exit 1)

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v3-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v3-

      - name: Cache Android SDK (tools/platforms)
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.ANDROID_HOME }}/platform-tools
            ${{ env.ANDROID_HOME }}/platforms/android-35
            ${{ env.ANDROID_HOME }}/emulator
            ${{ env.ANDROID_HOME }}/cmdline-tools
          key: ${{ runner.os }}-androidsdk-v2-35

      - name: Cache Android system image (API 35 google_apis arm64)
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.ANDROID_HOME }}/system-images/android-35/google_apis/arm64-v8a
          key: ${{ runner.os }}-sysimg-v2-android35-google_apis-arm64

      - name: Verify Android SDK tools
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          sdkmanager --version || true
          avdmanager --help || true

      - name: List Managed Device test tasks
        run: |
          ./gradlew :app:tasks --all | grep -E "DebugAndroidTest|Managed|Device" || true

      - name: Accept Android SDK licenses & install components (for Managed Devices)
        run: |
          set -e
          export ANDROID_SDK_ROOT="${ANDROID_HOME:-$ANDROID_SDK_ROOT}"

          # Resolve sdkmanager path explicitly (PATH may not include it on macOS runners)
          CANDIDATES=(
            "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager"
            "$ANDROID_HOME/cmdline-tools/bin/sdkmanager"
            "/usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager"
            "/usr/local/lib/android/sdk/cmdline-tools/bin/sdkmanager"
          )
          for c in "${CANDIDATES[@]}"; do
            if [ -x "$c" ]; then SDKM="$c"; break; fi
          done
          if [ -z "${SDKM:-}" ]; then
            echo "sdkmanager not found. Ensure cmdline-tools are installed on the runner." >&2
            echo "Checked: ${CANDIDATES[*]}" >&2
            exit 1
          fi

          echo "Using sdkmanager: $SDKM"

          yes | "$SDKM" --licenses
          yes | "$SDKM" --install \
            "platform-tools" \
            "platforms;android-35" \
            "emulator" \
            "system-images;android-35;google_apis;arm64-v8a"

          # List to verify (non-fatal)
          "$SDKM" --list | grep -E "android-35|google_apis|emulator" || true

      - name: Run instrumentation tests (Gradle Managed Devices)
        run: |
          echo "Running $MD_DEVICE_TASK"
          ./gradlew --stacktrace --info -Pandroid.experimental.testOptions.managedDevices.emulator.gpu=swiftshader_indirect $MD_DEVICE_TASK

      - name: Upload Android test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-test-results
          path: app/build/reports/androidTests/

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Force Gradle 8.13 and clear cache
        run: |
          echo "=== Before update ==="
          grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties
          ./gradlew --version || true
          
          echo "=== Clearing Gradle cache ==="
          rm -rf ~/.gradle/caches || true
          rm -rf ~/.gradle/wrapper || true
          rm -rf .gradle || true
          
          echo "=== Updating to Gradle 8.13 ==="
          sed -i.bak 's|gradle-.*-bin\.zip|gradle-8.13-bin.zip|' gradle/wrapper/gradle-wrapper.properties
          
          echo "=== After update ==="
          grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties
          
          echo "=== Downloading fresh Gradle ==="
          ./gradlew --version
          
          echo "=== Verifying Gradle version ==="
          ./gradlew --version | grep "Gradle 8.13" || (echo "ERROR: Gradle 8.13 not detected" && exit 1)

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v3-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v3-

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload lint reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-reports
          path: app/build/reports/