name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Force Gradle 8.13 and clear cache
        run: |
          echo "=== Before update ==="
          grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties
          ./gradlew --version || true
          
          echo "=== Clearing Gradle cache ==="
          rm -rf ~/.gradle/caches || true
          rm -rf ~/.gradle/wrapper || true
          rm -rf .gradle || true
          
          echo "=== Updating to Gradle 8.13 ==="
          sed -i.bak 's|gradle-.*-bin\.zip|gradle-8.13-bin.zip|' gradle/wrapper/gradle-wrapper.properties
          
          echo "=== After update ==="
          grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties
          
          echo "=== Downloading fresh Gradle ==="
          ./gradlew --version
          
          echo "=== Verifying Gradle version ==="
          ./gradlew --version | grep "Gradle 8.13" || (echo "ERROR: Gradle 8.13 not detected" && exit 1)

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v3-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v3-

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-outputs
          path: app/build/outputs/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: app/build/test-results/

  android-test:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Force Gradle 8.13 and clear cache
        run: |
          echo "=== Before update ==="
          grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties
          ./gradlew --version || true
          
          echo "=== Clearing Gradle cache ==="
          rm -rf ~/.gradle/caches || true
          rm -rf ~/.gradle/wrapper || true
          rm -rf .gradle || true
          
          echo "=== Updating to Gradle 8.13 ==="
          sed -i.bak 's|gradle-.*-bin\.zip|gradle-8.13-bin.zip|' gradle/wrapper/gradle-wrapper.properties
          
          echo "=== After update ==="
          grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties
          
          echo "=== Downloading fresh Gradle ==="
          ./gradlew --version
          
          echo "=== Verifying Gradle version ==="
          ./gradlew --version | grep "Gradle 8.13" || (echo "ERROR: Gradle 8.13 not detected" && exit 1)

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v3-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v3-

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-api34-arm64

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: arm64-v8a
          profile: pixel_7
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -memory 4096 -partition-size 2048
          disable-animations: false
          emulator-boot-timeout: 900
          script: echo "Generated AVD snapshot for caching."

      - name: Run Android instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: arm64-v8a
          profile: pixel_7
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -memory 4096 -partition-size 2048
          disable-animations: true
          emulator-boot-timeout: 900
          script: |
            adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\''\r'\'') ]]; do sleep 1; done; input keyevent 82'
            ./gradlew connectedDebugAndroidTest

      - name: Upload Android test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-test-results
          path: app/build/reports/androidTests/

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Force Gradle 8.13 and clear cache
        run: |
          echo "=== Before update ==="
          grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties
          ./gradlew --version || true
          
          echo "=== Clearing Gradle cache ==="
          rm -rf ~/.gradle/caches || true
          rm -rf ~/.gradle/wrapper || true
          rm -rf .gradle || true
          
          echo "=== Updating to Gradle 8.13 ==="
          sed -i.bak 's|gradle-.*-bin\.zip|gradle-8.13-bin.zip|' gradle/wrapper/gradle-wrapper.properties
          
          echo "=== After update ==="
          grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties
          
          echo "=== Downloading fresh Gradle ==="
          ./gradlew --version
          
          echo "=== Verifying Gradle version ==="
          ./gradlew --version | grep "Gradle 8.13" || (echo "ERROR: Gradle 8.13 not detected" && exit 1)

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v3-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v3-

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload lint reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-reports
          path: app/build/reports/